# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_location',
            field=models.CharField(choices=[('Kibera', 'KIBERA'), ('Dandora', 'DANDORA')], max_length=40),
        ),
    ]
