# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20190117_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
